/* Daftar kitab Alkitab dengan jumlah pasal. Sumber: erwindosianipar/api-alkitab (list_passage.csv). */
export type BibleBook = { id: number; abbr: string; name: string; chapters: number; testament: "PL" | "PB" };
export const bibleBooks: BibleBook[] = [
  { id: 1, abbr: "Kej", name: "Kejadian", chapters: 50, testament: "PL" },
  { id: 2, abbr: "Kel", name: "Keluaran", chapters: 40, testament: "PL" },
  { id: 3, abbr: "Ima", name: "Imamat", chapters: 27, testament: "PL" },
  { id: 4, abbr: "Bil", name: "Bilangan", chapters: 36, testament: "PL" },
  { id: 5, abbr: "Ula", name: "Ulangan", chapters: 34, testament: "PL" },
  { id: 6, abbr: "Yos", name: "Yosua", chapters: 24, testament: "PL" },
  { id: 7, abbr: "Hak", name: "Hakim-hakim", chapters: 21, testament: "PL" },
  { id: 8, abbr: "Rut", name: "Rut", chapters: 4, testament: "PL" },
  { id: 9, abbr: "1 Sam", name: "1 Samuel", chapters: 31, testament: "PL" },
  { id: 10, abbr: "2 Sam", name: "2 Samuel", chapters: 24, testament: "PL" },
  { id: 11, abbr: "1 Raj", name: "1 Raja-Raja", chapters: 22, testament: "PL" },
  { id: 12, abbr: "2 Raj", name: "2 Raja-Raja", chapters: 25, testament: "PL" },
  { id: 13, abbr: "1 Taw", name: "1 Tawarikh", chapters: 29, testament: "PL" },
  { id: 14, abbr: "2 Taw", name: "2 Tawarikh", chapters: 36, testament: "PL" },
  { id: 15, abbr: "Ezr", name: "Ezra", chapters: 10, testament: "PL" },
  { id: 16, abbr: "Neh", name: "Nehemia", chapters: 13, testament: "PL" },
  { id: 17, abbr: "Est", name: "Ester", chapters: 10, testament: "PL" },
  { id: 18, abbr: "Ayb", name: "Ayub", chapters: 42, testament: "PL" },
  { id: 19, abbr: "Maz", name: "Mazmur", chapters: 150, testament: "PL" },
  { id: 20, abbr: "Ams", name: "Amsal", chapters: 31, testament: "PL" },
  { id: 21, abbr: "Pkh", name: "Pengkhotbah", chapters: 12, testament: "PL" },
  { id: 22, abbr: "Kid", name: "Kidung Agung", chapters: 8, testament: "PL" },
  { id: 23, abbr: "Yes", name: "Yesaya", chapters: 66, testament: "PL" },
  { id: 24, abbr: "Yer", name: "Yeremia", chapters: 52, testament: "PL" },
  { id: 25, abbr: "Rat", name: "Ratapan", chapters: 5, testament: "PL" },
  { id: 26, abbr: "Yeh", name: "Yehezkiel", chapters: 48, testament: "PL" },
  { id: 27, abbr: "Dan", name: "Daniel", chapters: 12, testament: "PL" },
  { id: 28, abbr: "Hos", name: "Hosea", chapters: 14, testament: "PL" },
  { id: 29, abbr: "Yoe", name: "Yoel", chapters: 3, testament: "PL" },
  { id: 30, abbr: "Amo", name: "Amos", chapters: 9, testament: "PL" },
  { id: 31, abbr: "Oba", name: "Obaja", chapters: 1, testament: "PL" },
  { id: 32, abbr: "Yun", name: "Yunus", chapters: 4, testament: "PL" },
  { id: 33, abbr: "Mik", name: "Mikha", chapters: 7, testament: "PL" },
  { id: 34, abbr: "Nah", name: "Nahum", chapters: 3, testament: "PL" },
  { id: 35, abbr: "Hab", name: "Habakuk", chapters: 3, testament: "PL" },
  { id: 36, abbr: "Zef", name: "Zefanya", chapters: 3, testament: "PL" },
  { id: 37, abbr: "Hag", name: "Hagai", chapters: 2, testament: "PL" },
  { id: 38, abbr: "Zak", name: "Zakharia", chapters: 14, testament: "PL" },
  { id: 39, abbr: "Mal", name: "Maleakhi", chapters: 4, testament: "PL" },
  { id: 40, abbr: "Mat", name: "Matius", chapters: 28, testament: "PB" },
  { id: 41, abbr: "Mar", name: "Markus", chapters: 16, testament: "PB" },
  { id: 42, abbr: "Luk", name: "Lukas", chapters: 24, testament: "PB" },
  { id: 43, abbr: "Yoh", name: "Yohanes", chapters: 21, testament: "PB" },
  { id: 44, abbr: "Kis", name: "Kisah Para Rasul", chapters: 28, testament: "PB" },
  { id: 45, abbr: "Rom", name: "Roma", chapters: 16, testament: "PB" },
  { id: 46, abbr: "1 Kor", name: "1 Korintus", chapters: 16, testament: "PB" },
  { id: 47, abbr: "2 Kor", name: "2 Korintus", chapters: 13, testament: "PB" },
  { id: 48, abbr: "Gal", name: "Galatia", chapters: 6, testament: "PB" },
  { id: 49, abbr: "Efe", name: "Efesus", chapters: 6, testament: "PB" },
  { id: 50, abbr: "Flp", name: "Filipi", chapters: 4, testament: "PB" },
  { id: 51, abbr: "Kol", name: "Kolose", chapters: 4, testament: "PB" },
  { id: 52, abbr: "1 Tes", name: "1 Tesalonika", chapters: 5, testament: "PB" },
  { id: 53, abbr: "2 Tes", name: "2 Tesalonika", chapters: 3, testament: "PB" },
  { id: 54, abbr: "1 Tim", name: "1 Timotius", chapters: 6, testament: "PB" },
  { id: 55, abbr: "2 Tim", name: "2 Timotius", chapters: 4, testament: "PB" },
  { id: 56, abbr: "Tit", name: "Titus", chapters: 3, testament: "PB" },
  { id: 57, abbr: "Flm", name: "Filemon", chapters: 1, testament: "PB" },
  { id: 58, abbr: "Ibr", name: "Ibrani", chapters: 13, testament: "PB" },
  { id: 59, abbr: "Yak", name: "Yakobus", chapters: 5, testament: "PB" },
  { id: 60, abbr: "1 Pet", name: "1 Petrus", chapters: 5, testament: "PB" },
  { id: 61, abbr: "2 Pet", name: "2 Petrus", chapters: 3, testament: "PB" },
  { id: 62, abbr: "1 Yoh", name: "1 Yohanes", chapters: 5, testament: "PB" },
  { id: 63, abbr: "2 Yoh", name: "2 Yohanes", chapters: 1, testament: "PB" },
  { id: 64, abbr: "3 Yoh", name: "3 Yohanes", chapters: 1, testament: "PB" },
  { id: 65, abbr: "Yud", name: "Yudas", chapters: 1, testament: "PB" },
  { id: 66, abbr: "Wah", name: "Wahyu", chapters: 22, testament: "PB" },
];
export const bibleVersions = [
  { code: "tb", label: "Terjemahan Baru", short: "TB" },
  { code: "tl", label: "Terjemahan Lama", short: "TL" },
  { code: "toba", label: "Batak Toba", short: "BBT" },
];
